version: '2.2'

services:

  geth:
    image: ethereum/client-go:latest
    command: --goerli --metrics --metrics.expensive --pprof --pprofaddr=0.0.0.0

  prometheus:
    image: prom/prometheus
    depends_on:
      geth:
        condition: service_started
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
